### PR TITLE
feat(checksums): add SHA256 checks to Dockerfiles

### PR DESCRIPTION
**Pull request by blairdrummond**
Adds sha256 checks, plus a helper script  `.checksums/checksums.sh` which fetches the latest versions of the software from the varies sources, and records the version numbers and shas, so that continued updating is simpler.

### CODE REVIEW

**Comment by blairdrummond** [comment]
@justbert  Do you know what this error indicates?

```
Run Azure/container-scan@v0
Could not find allowedlist file.
/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/c3f789eb-238c-4304-8413-b2967bf4efb2 -f /home/runner/work/kubeflow-containers/kubeflow-containers/_temp/tools/trivy
Scanning for vulnerabilties...
##[error]FATAL	unable to initialize a scanner: unable to initialize a docker scanner: 2 errors occurred:
##[error]An error occured while scanning the container image for vulnerabilities
```

**Comment by justbert** [comment]
Hmmm... Not me.

@sylus or @zachomedia?

**Comment by blairdrummond** [comment]
Oh! Duh. The images are not being pushed into a registry, so of course container scanning isn't going to work...

**Comment by justbert** [comment]
Oh right! So much sense!

**Comment by blairdrummond** [comment]
First image successfully scanned. Looks like it's chugging along now!

**Comment by blairdrummond** [comment]
@sylus ; I built `base/cpu`, `minimal/cpu` and `rstudio` on my personal machine this morning. All building.

**Comment by sylus** [comment]
This looks pretty good to me and definitely is good to check the SHA shows a bit more maturity on our side so awesome work!

I'd need @zachomedia to +1 this but I like it :)

**Pull request merged**
