### PR TITLE
fix: Pin an older version of pytorch/accessories to fix build

### LINKED ISSUE #181: Fix failing pytorch builds
In the past ~week or two an unpinned dependency changed in the pytorch stack, causing CI failures.  This blocks building for all pytorch images.

### PR DESCRIPTION
**Pull request by ca-scribner**
fixes #181

### CODE REVIEW

**Comment by ca-scribner** [comment]
resolves #181

**Review by sylus — APPROVED** [review]

**Review by sylus — CHANGES_REQUESTED** [review]
I notice we changed pytorch-gpu to just pytorch?

**Comment by ca-scribner** [comment]
#I think pytorch-gpu is a legacy thing that doesnt matter anymore. The pytorch getting started guide installs cuda without the `-gpu`

**Comment by ca-scribner** [comment]
Actually I think installing cudnn drivers entirely is unnecessary now. Seems like conda can handle it all. Made a note to try it after holidays

**Pull request merged**
