### PR TITLE
Refactor and streamline builds using Matrix Strategy

### PR DESCRIPTION
**Pull request by sylus**
In general I and @zachomedia are a fan of this approach, and think it hits a few of the pain points:

a) All are based on a single template
b) The final output is still exported and stored in Git
c) All of the builds are done in a Matrix Strategy
d) The CI run finishes in about 40 minutes

> Thanks @blairdrummond for working on this and proposing this P.R.

Screen Shot 2020-11-26 at 3 03 06 PM

### CODE REVIEW

**Comment by sylus** [comment]
@blairdrummond is the CUDA bug fixed here for the GPU images as well?

**Comment by blairdrummond** [comment]
@sylus I'd appreciate @ca-scribner 's review on the GPU bugs to see, but I think yes:

Screenshot from 2020-11-15 16-33-39

Screenshot from 2020-11-15 11-05-23

**Comment by sylus** [comment]
@brendangadd is there additional information and / or question you require for this for us to accept this approach?

**Comment by ca-scribner** [comment]
migrating some comments over from #159:

@sylus @zachomedia when Blair walked me through this and I was torn. I really liked how it made it easy to identify and maintain the install instructions for various mixins (eg: Installing jupyterlab? go to docker-bits/6_JupyterLab.Dockerfile), but it also felt like it side steps some benefits of Docker (ex: mixins lead to many more layers because we aren't combining dissimilar installs into the same RUN, layer caching gets less transparent, ...).

I also worried it made it harder for someone new to join in and contribute (need to learn the makefile structure, etc). But counter to that, maintenance of each individual piece because far easier and more transparent, so maybe it is a net positive.

Am I worried about nothing, or do you have suggestions to work around this?

Suggestion for **Blair**: one thing I've seen some other dockerfile-orchestrating repos do that is nice is put the output into a .output or .build folder to make it a bit clearer that that content is more a product than something people should directly change. They also had a readme in the .build folder stating the files were auto generated, and ideally a header in each the Dockerfiles saying they were autogenerated).

**Comment by ca-scribner** [comment]
@sylus this does install the missing CUDNN drivers.  I **think** it works, but I'm not sure.  The CUDNN drivers get installed after a lot of other stuff instead of at the top in the NVIDIA-provided base image, and I don't know if that's a problem.  Do you?  If installing the NVIDIA drivers that late is ok, why does [gpu-jupyter](https://github.com/iot-salzburg/gpu-jupyter) exist at all?

**Comment by ca-scribner** [comment]
If we decide to go with this, I think there's still some refactoring to discuss.  The r-studio image now has spark, the CUDA driver version is bumped, and I think there's some other stuff add/subtracted, so someone should review with software and versions in mind.

**Comment by ca-scribner** [comment]
I think I like this approach better if we refactor to be a full mixin approach rather than a hybrid mixin/dag.  The `docker-bits` shouldn't assume the order/mutual-exclusivity of how `Dockerfile` snippets go together.  Instead it should be a repo of `Dockerfile` snippets for each software/version (and maybe a `latest` that points to the latest snippet for each), so something like:
- nvidia drivers
  - 10.0
    - Dockerfile.snippet
    - ..any other supporting files that should be in the build context
  - 11.0
    - Dockerfile.snippet
    - ...
  - latest
    - points to 11.0 or whatever we want `latest` to build from, giving us an easy way to update all images that we want to always be up to date

Then separately (but maybe in same repo) we can have a collection of template files that represent the different end products (`minimal-notebook-cpu`, `machine-learning-gpu`, ...).  Each template definition can include an ordered list of the `snippets` that form their output, then the build makefile can be in charge of executing the build of all templates.  That way, just like we've encapsulated the definition of each software's Docker definition into easy to find pieces, we do the same to the DAG that defines the actual `Dockerfile`.  So something like this:
- templates
  - minimal-notebook-cpu
    - definitionFile
- templates
  - minimal-notebook-gpu
    - definitionFile
- ...

where `minimal-notebook-gpu`'s definitionFile could be:
```
nvidia_drivers/11.0
kubeflow/latest
tensorflow/2.3.0
...
```

...ideally I'd actually like to be able to refer to a past definition file in there too, that way we could benefit from intermediate Dockerfiles in addition to the nice and maintainable snippets.  Something like:
```
templates/minimal-notebook-gpu
someAdditionalSoftware/latest
...
```

**Comment by blairdrummond** [comment]
@ca-scribner 

## Layers

- All layers shared within the docker-bits will be shared in the ACR, if possible. E.g VSCode-Spark and JupyterLab-Spark will share everything up to the UI. 

- The layers *are* built on many machine in parallel at once (which is redundant, true), but that's what lets the failure-free parallel CI process work, and the images are built faster as a result.
 
- Also, the compute time is free on public github actions (plus, it only takes 40 minutes to build **everything** anyway).

## GPU
- I have screenshots there of PyTorch and Tensorflow using the GPU... If you have another test-case to run then we can check that?
- The NVidia base images are super simple when you dig into them. I read through their image hierarchy. [repo](https://gitlab.com/nvidia/container-images/cuda/-/blob/master/dist/11.1/ubuntu18.04-x86_64/runtime/cudnn8/Dockerfile)
- I really don't think we're missing anything there...

## On templates
I have to hard-disagree on the template-per-target thing. 

- I think having a single template engine is much simpler, and means that changes only need to be made "locally". One of the aims of this design was to minimize duplication.
- Inheritance and template-per-target both struggle with multiplication. The DAG in docker-bits is really letting you "multiply" features, without multiplying the amount of maintained boiler-plate code.

## DAGs are our friend

- Also, the sequence of application is important. It's good to be clear what order things get applied in.
- Some steps are mutually exclusive, so the convention that you only take one `docker-bit` from any layer of the DAG seems nice.

## Indicate that the output files are generated
Sure thing. I'm not gonna muck around in @sylus 's PR, but we can add more documentation. Sounds like we could add that to the Makefile output target.

```Makefile
.output:
    mkdir -p $(OUT)/ $(TMP)/
    echo "\# These files are automatically generated" > $(OUT)/README.md
    echo 'Treat these as "read only" and modify the `docker-bits` instead. Then compile with `make all`'  >> $(OUT)/README.md
```

# Feature Related Changes

I 100% agree, there are feature changes that deserve discussion. For example:

- I added conda-environment notebooks.
- The visuals of Conda environments in Notebooks could be nicer. But I think this is relatively minor.
- Yes, Spark is in the R image, I added it for Spark-R.
- I made zsh (actually oh-my-zsh) the default shell, and they start in a conda environment with minio auto-loaded.
- I added [Pluto.jl](https://github.com/fonsp/Pluto.jl) for Julia notebooks, which was requested in the AAW slack channel by a user.
- I added VS-Code, of course.
- I added [PGWeb](http://sosedoff.github.io/pgweb/) since Postgres for geospatial is on the horizon (and also, a client doesn't hurt anyone.)
- I removed the azcli pin.
- :warning: I unpinned the JupyterLab extensions. They were (predictably) breaking, so I built without pins, but can test the components and repin with the new versions.

# Conclusion

I can pull the new features out and add them as a separate PR for review, but I stand by the structure here.

**Comment by blairdrummond** [comment]
Resolves #150 , #147 , #137 , #136 , #122 , #121 , #107  , #27 , #48 ,

**Review by zachomedia — APPROVED** [review]
This is LGTM. Let's merge and go from there!

**Pull request merged**
