### PR TITLE
added kubeflow notebook examples

### PR DESCRIPTION
**Pull request by chritter**
Added getting-started notebook and notebook with ML examples. Major packages requires are TensorFlow, PyTorch and Scikit-learn.

### CODE REVIEW

**Comment by sylus** [comment]
Can look at merging this soon just not sure how to do it yet as don't want it to build the containers when just the notebooks are updated. Think a github action for that but need to look into it.

**Comment by chritter** [comment]
@sylus Expect further requests as I am working on KF pipelines examples.

**Comment by blairdrummond** [comment]
@sylus To avoid this issue, what if we replace the CMD with a (metaphorically) CMD="git pull statcan/kubeflow-example-notebooks; $CMD"

If you create a repo and gave us access, we could work on those over the weekend and they'll just be pulled at run-time. What do you think?

**Comment by sylus** [comment]
Hey @blairdrummond yeah I think that might be a better idea, does this work?

https://github.com/StatCan/jupyter-notebooks

**Comment by sylus** [comment]
Let me know if does @blairdrummond @chritter

**Comment by blairdrummond** [comment]
@sylus Yeah that'll be great. I'll coordinate with @chritter to update that repo.

Let me know when you get the chance to add the `git pull` into the `CMD`

**Comment by sylus** [comment]
This is now added and once build done will pull from https://github.com/StatCan/jupyter-notebooks

**Pull request closed without merging**
