### PR TITLE
remove duplicate installations

### PR DESCRIPTION
**Pull request by saffaalvi**
Resolves https://github.com/StatCan/kubeflow-containers/issues/110

### CODE REVIEW

**Comment by ca-scribner** [comment]
@saffaalvi does this need a rebase on master before merging?  It might be conflicting with the pachctl removal that is merged into master now?

**Comment by ca-scribner** [comment]
@blairdrummond saffa noticed we do this in `r-studio`:
```
ARG KUBECTL_VERSION=v1.15.10	
ARG KUBECTL_URL=https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl	
ARG KUBECTL_SHA=38a0f73464f1c39ca383fd43196f84bdbe6e553fe3e677b6e7012ef7ad5eaf2b	

ARG MC_VERSION=mc.RELEASE.2020-06-20T00-18-43Z	
ARG MC_URL=https://dl.min.io/client/mc/release/linux-amd64/archive/${MC_VERSION}	
ARG MC_SHA=7198b0634f84c27e656bba527bf80ed048087e99afc7744e0fdd9e0790a726f5	

ARG AZCLI_URL=https://aka.ms/InstallAzureCLIDeb 	
ARG AZCLI_SHA=c03302f47be07d02afe3edec63080c7806980c51709c016af2f27901d51417b4	

ARG PACHCTL_VERSION=1.10.5	
ARG PACHCTL_URL=https://github.com/pachyderm/pachyderm/releases/download/v${PACHCTL_VERSION}/pachctl_${PACHCTL_VERSION}_amd64.deb 	
ARG PACHCTL_SHA=8bc58206e87c3c4304a074c1479e08bdf173743dd6869d0ad4e792830a0df5c5
```
but the upstream notebook ([minimal](https://github.com/StatCan/kubeflow-containers/blob/9a9c54cc0464dab5a3f81da7c8f01a6fff30cc81/minimal-notebook/cpu/Dockerfile)) hast the same code already.  Was there a reason we did it twice?  If not she'll remove from here and rely on `minimal`'s version

**Comment by blairdrummond** [comment]
@ca-scribner @saffaalvi ; originally `r-studio` did not derive from `minimal` at all, but from a different image in `docker-stacks`. So I guess someone rebased this image onto minimal and then the code was duplicated as a result.

FYI, those shas come from here:

https://github.com/StatCan/kubeflow-containers/tree/master/.checksum-checks

**Comment by blairdrummond** [comment]
(Sorry, clicked the wrong button lol)

**Comment by ca-scribner** [comment]
haha @blairdrummond no I don't think its a problem **MIC DROP CONVERSATION DONE**  :heart:

**Pull request closed without merging**
