### PR TITLE
feat: add /proxy for remote-desktop

### LINKED ISSUE #261: Add /proxy for remote-desktop image
Addresses the regression of the `/tools` url, and this lets the new remote-desktop implement parity with the old images in kubeflow-containers-desktop.

### PR DESCRIPTION
**Pull request by blairdrummond**
Proxy works! :-D 

Screenshot from 2021-05-18 15-13-05

Closes #261

### CODE REVIEW

**Review by ca-scribner — APPROVED** [review]
lgtm

**Comment by blairdrummond** [comment]
Closes  #261

**Review by brendangadd — CHANGES_REQUESTED** [review]
@blairdrummond Can you review the config against _[Common Nginx misconfigurations that leave your web server open to attack](https://blog.detectify.com/2020/11/10/common-nginx-misconfigurations/)_?

I did a very quick scan, and I do see the use of `$uri` in the config, which should maybe be replaced with `$request_uri`.

**Comment by blairdrummond** [comment]
@brendangadd I did replace half, of them, but the `location /` block comes from the [novnc info](https://github.com/novnc/noVNC/wiki/Proxying-with-nginx) and doesn't seem to work when using the `$request_uri`

**Review by brendangadd — APPROVED** [review]

**Pull request merged**
